
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tweetapp_development


test:
  <<: *default
  database: tweetapp_test


production:
  <<: *default
  database: tweetapp_production
  username: tweetapp
  password: <%= ENV['TWEETAPP_DATABASE_PASSWORD'] %>
